steps:
# Build the Go binary
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'helloserver', '.']

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloserver:$COMMIT_SHA', '.']

# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/helloserver:$COMMIT_SHA']

# Deploy the application to Cloud Run (adjust the service name and region)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'helloserver'
    - '--image=gcr.io/$PROJECT_ID/helloserver:$COMMIT_SHA'
    - '--platform=managed'
    - '--region=us-central1'  # Adjust the region as needed

